server:
  port: 5000
spring:
  datasource:
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/mall-shop?useSSL=false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
mall:
  security:
    jwt-key: mall-shopping
    token-expired-time: 86400000
    default-scope: 8
  order:
    pay-time-limit: 3600
    max-sku-limit: 500
pulsar:
  service-url: pulsar://localhost:6650
  listener-thread-num: 5
  mall-order-topic: mall-order-topic
  mall-order-producer-name: ${spring.application.name}-order-producer
  mall-order-consumer-name: ${spring.application.name}-order-consumer
  mall-order-subscription-name: ${spring.application.name}-order-subscription
wx:
  code2-session-url: 123
  appid: 123
  appsecret: 123
